# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1817465ff90ab691856cbe191c4c4a86c417195cf5e5d6ed3189c6106b0203170a257787cb9dd0d6ddd144824edc636a39f705349dc1875e70bcb73c677a1918

test:
  secret_key_base: 0696cf0354d101be660cf028b7dd6746649362548494e5e95eb2ce571b6b19173bf17f6c11a7e3b78dd731704701af5c4992cb6e8a1e99b2653e1c7fc09a9ee1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
